version: '3.1'

services:
  va-db:
    image: postgres:latest
    container_name: va-db 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - va_network
    volumes:
      - ./postgresql-volume:/var/lib/postgresql/data

networks:
  va_network:
    driver: bridge
