version: '3.1'

services:
  va-db:
    image: mysql:latest
    container_name: va-db 
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - va_network
    volumes:
      - ./mysql-volume:/var/lib/mysql

networks:
  va_network:
    driver: bridge